/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package leksjon8_app;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Grethe
 */
public class leksjon8_GUI extends javax.swing.JFrame {

    /**
     * Creates new form leksjon8_GUI
     */
    private Database databasen;
    private DefaultListModel listeinnhold = new DefaultListModel();

    public leksjon8_GUI() {
        initComponents();
        /*
         * Applications no longer need to explictly load JDBC drivers using Class.forName().
         * String databasedriver = "org.apache.derby.jdbc.ClientDriver";  
        */
        String databaseurl = "jdbc:derby://localhost:1527/persondata;user=waplj;password=waplj";  // jdbc:subprotocol:subname
        try {
            databasen = new Database(databaseurl);
            fyllListeMedData();
            liste.setModel(listeinnhold);
        } catch (Exception e) {
            System.out.println("Fikk ikke opprettet database-objektet" + e.getMessage());
        }
    }

    private void fyllListeMedData() {
        listeinnhold.clear();
        ArrayList<Person> alle = databasen.getAllePersoner();
        if (alle != null) {
            for (Person p : alle) {
                listeinnhold.addElement(p);
            }
            if (listeinnhold.size() > 0) {
                liste.setSelectedIndex(0);
            } else {
                btnEndre.setEnabled(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnslett = new javax.swing.JButton();
        btnNy = new javax.swing.JButton();
        btnEndre = new javax.swing.JButton();
        btnGjennoppfrisk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        liste = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Brush Script Std", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Vedlikehold av navneregister");

        btnslett.setText("Slett");
        btnslett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnslettActionPerformed(evt);
            }
        });

        btnNy.setText("Ny");
        btnNy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyActionPerformed(evt);
            }
        });

        btnEndre.setText("Endre");
        btnEndre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndreActionPerformed(evt);
            }
        });

        btnGjennoppfrisk.setText("Gjenoppfrisk");
        btnGjennoppfrisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGjennoppfriskActionPerformed(evt);
            }
        });

        liste.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liste);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnslett, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnNy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEndre, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGjennoppfrisk))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnslett)
                    .addComponent(btnNy)
                    .addComponent(btnEndre)
                    .addComponent(btnGjennoppfrisk))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnslettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnslettActionPerformed
        // Slette valgt person
        Person p = (Person) liste.getSelectedValue();
        int index = liste.getSelectedIndex();

        boolean slettet = databasen.slettPerson(p);
        if (slettet) {
            listeinnhold.remove(index);
            if (listeinnhold.size() > 0) {
                liste.setSelectedIndex(0);
            } else {
                btnEndre.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Får ikke slettet personen, kan være slettet av andre");
        }
    }//GEN-LAST:event_btnslettActionPerformed

    private void btnNyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyActionPerformed
        /* Registrerer to personer - en på "gammel-måten" vha JOptionPane,
         * en vha av et dialogvindu
        */
        //Registrer ny person
        String fornavn = JOptionPane.showInputDialog(rootPane, "Endre fornavn:");
        String etternavn = JOptionPane.showInputDialog(rootPane, "Endre etternavn:");
        Person p = new Person(-1, fornavn.toUpperCase(), etternavn.toUpperCase());
        if (databasen.regPerson(p)) {
            listeinnhold.addElement(p);
            JOptionPane.showMessageDialog(rootPane, "Person registrert: " + p);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Noe gikk galt under registrering");
        }
        if (listeinnhold.size() == 0) {
            btnEndre.setEnabled(true);
        }

        // Bruker en dialog istedet;
        persondialog pd = new persondialog(this, true);
        p = pd.showDialog();
        if (databasen.regPerson(p)) {
            listeinnhold.addElement(p);
            JOptionPane.showMessageDialog(rootPane, "Person registrert: " + p);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Noe gikk galt under registrert: ");
        }
        if (listeinnhold.size() == 0) {
            btnEndre.setEnabled(true);
        }


    }//GEN-LAST:event_btnNyActionPerformed

    private void btnEndreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndreActionPerformed
        // Endrer et navn
        Person p = (Person) liste.getSelectedValue();
        int index = liste.getSelectedIndex();
        String fornavn = JOptionPane.showInputDialog(rootPane, "Endre fornavn", p.getFornavn());
        String etternavn = JOptionPane.showInputDialog(rootPane, "Endre etternavn", p.getEtternavn());
        p.setFornavn(fornavn.toUpperCase());
        p.setEtternavn(etternavn.toUpperCase());
        if (databasen.updatePerson(p)) {
            listeinnhold.set(index, p);
            liste.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnEndreActionPerformed

    private void btnGjennoppfriskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGjennoppfriskActionPerformed
        // Henter "friske" data fra databasen
        fyllListeMedData();
    }//GEN-LAST:event_btnGjennoppfriskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leksjon8_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leksjon8_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leksjon8_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leksjon8_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leksjon8_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEndre;
    private javax.swing.JButton btnGjennoppfrisk;
    private javax.swing.JButton btnNy;
    private javax.swing.JButton btnslett;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList liste;
    // End of variables declaration//GEN-END:variables
}
